### ISSUE TITLE
Private endpoints can't communicate with private endpoints in other public gateways

### ISSUE THREAD

**Issue by gnarea** [relaynet/specs#74]
# Executive summary

Parcels produced by private endpoints don't have enough information for the public gateway to route it to another public gateway. Such parcels can only be routed to a public endpoint or another private endpoint behind the same public gateway.

# Proposed solution

Require parcels to specify a public address as the recipient. When the recipient is a private endpoint, the recipient address will be the public gateway for the target endpoint. When the recipient is a public endpoint, the recipient address will continue to be the public address of that endpoint (as it is today).

# TODO

- [x] RAMF message addressing.
- [x] RAMF format signature constant: "Relaynet" is now "Awala"
- [x] Rename "private address" to "id"
- [x] Rename "public $node" to "Internet $node"
- [x] (PoHTTP) No more sending of public gateway's public address.
- [x] (PoHTTP) `202` for mismatching private address (because it's not the gateway's fault), but keep `403` for mismatching Internet address (because that is the gateway's fault).
- [x] Ping: Add `endpoint_internet_address`
